### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by Carbon-404**
First version of the game

### CODE REVIEW

**Review by T3rryc — APPROVED** [review]

**Review by AlexisLasselin — APPROVED** [review]
LGTM 👌

**Review by HiNett — APPROVED** [review]
Thanks for asking me. I approve

**Review by RemyCHARLES — APPROVED** [review]
Very well done!

**Review by T3rryc — APPROVED** [review]

**Review by Pierre2103 — APPROVED** [review]

**Comment by HiNett** [comment]
Forget it, thanks for your contribution.

**Review by HiNett — APPROVED** [review]
I do approve again.

**Review by HiNett — APPROVED** [review]
I think I'll approve again, it's only the third time after all.

**Review by T3rryc — APPROVED** [review]

**Review by AlexisLasselin — APPROVED** [review]
lgfm

**Review by RemyCHARLES — APPROVED** [review]
I approve with my consent.

**Review by Pierre2103 — APPROVED** [review]
👍

**Pull request merged**
